channels:
- conda-forge
dependencies:
- python=3.12
- pyiron_base=0.11.7
- qe=7.2
- qe-tools=2.0.0
- ase=3.24.0
- matplotlib=3.10.1
- xmlschema=3.4.2
- jobflow=0.1.19
- pymatgen=2024.10.29
- aiida-core=2.6.3
- aiida-shell=0.8.0
